@startuml
sprite $combiner_1 [150x390/16z] {
nDQ9hhCw30JWKn8lCqxe-x_jJLpGVpPwDsX74cMJyibn4pwkI55ugKwQcBbhBMNvU7DkmjvPXK6hPe0MCIctjwFkzrPdhRIQ0dLHKodlLTbGhKsACrpTKZLI
twfQ36rTcogZqTtXMbKbLMzCJPLej8SA9kegovjhrTOvW_P99J1zRxiBVwYgmEoznTBMXog-gTpq8jLIH6r6fIo7ys6jfKg_rkeYrQAOmp23N1QVgDfhLBSv
CoiTCKCtBSzhPQzGBR6EmMYxobsNPxKoRwq57AJBPTrUOhqFbOExoWvLlVS06Ir81g4ADxbTeMhtJSMfWhkLOrLh11ZqUOJZMbK3E8DdgcHfHOHLDK2hkLsa
Yj4jlKMQ2E98fH6ZiPeKZx2Y2g-BcaYzI3LGhGNXMR2ZlbeCiTxxLvMANBCmzFkQQS6Pe1qi3Oj_KNcghYlL_TxRseEHdHC-1lfjgBAfSBrgOHz3kKTadQ8d
QqP4T6Ryrenuz4ygRAgBDjrr3JD6C1CjNAV8oNrXjH4tH_JFVNLHhJA5iwLoybgBUH8sgwE8bY7W8m0O_MTVQItB-J1fVM88HW2SInArxgfn5OIRSoPLYqTe
4PagCGFyWat7iXg08sZsODbKUOpJJUM88C6sjaygAUeC0f1_zRSldygxbEzPvYqZuHbW7XZ1hQyYGtYgjgQhnSc7ocox3xdzSvCOHhOFwqNir_WZ-RjVcUQJ
FP_EuIesN_ZwXjOV6GMvxP1bMVRpOW0PXAk8YhhRQwFrDlAngBdRLflY11xTIioulJfPKNTaaNCNlncpS_lQS-P9jvmOVKNsvW18x5DMHzr0jk20hK4cpFI5
IHKOGKVaHWOh7vLWWoFwsiY85hYaJl8pkiKc9zoHos2Zoqr81e2OrxdlmlGrAlci8W0pn2oMBfMCO7g2QDDcfsh-YQhrJX3kZDO3jfGWMunC54zNVVgWUAuA
1m7EghcL9RQ92sBMRsquMoLFKQbQUmEsJG6kPM6FnoI2qKS29_VJZZgMUQnh3p1cu3PKc0jefBEFXvr-QbFjOpzJ6SV8ZLaj-AuQhfc-9jdExgfv-0V5oXxo
nmVFWjHiwMTsbSpiPuVPEslTvWok3zLWtTVxFIlbTdQhPuwdKNTMkbh0KXN9oaBnh7NTr4mr8Jc16JjMgI6xkWNSJ8UAZ4UOTqvI9IjLC_PSDGxcY9O67weA
mZD9iZFcRLVbOJ_FaqDLlkk0JvGK_Vn5bQXJLBPxTfKyKOr3dcpqMek1i94pbyozvBjAzBXMF-icG-MyI2NofrR_L9MfgGBCJjvUjjDDy-TN_h4ALwZoaDcA
9td-NjMUlF7dzD-eY9DGnuluN-pSwtBag184u0XJcLa5xJdl_xPdKJ1NrclJQcIcJMulZURwHL4bwTTmo3L7XG73PRLgdlcgyq4ZVw3dBQMckZGVKiMxAb2k
3vS4_PFw2DhbkohxeChBBVGG5S17gPZ_zws8TqOT-q6gUBt5M6ztcQ2IkqP08C1sLWFtYaurTxOUhfAhhO1S2wZQzBKPXCejQmKLyxTl-LYB67LTGtLCNxo-
nh7c0T14bTp5jhAk2wZwBAMIj9mAVhk5hbNbTrHj4ZN4cL-hDeFBgUZYWYhoMbNCKyslrLQbWHFSgdNxohTgtqKVhyehgl9TAinpMJfHgqx5HwhEp22cv3uL
vghib0e_LMsxtWakg-BkzZSyTLbDDSy4swgjMlP-zN3UtFlLLW5_Yufhd20cncQfjcghShWM07Mr-fAghHhWRHMMKM75liAIgf-agRYbL5krLS1NLR4FrbJX
4XNNLF6CwZnigxPggxPggr0pNMLFgTgghSA96SHQglad-AGguEzKRTKuRwlGmLPGyUzNRHMEx5fjrSzy2HMvZ0f_N2wWwe85LOlq5PPJeMQv6UnbEC9FLW4a
ZhKj0wPPgiReBW5-fWedCb5bAIMhd_hVVR67FvsHQeoII1nRil5UwcNzCP8uhb_-DMcEog94kKNEbfANdED07JLKM4BEKVGFATLSfagHcGkzMDqQ2XrmA6Sg
MxBYp6gWZZInLhVy-ffBGVrzPaLPA93VtAlgLlBDwm6UEa4RL24xSY4BMwsKnHiZDrLnH1xgApn0PRdasslEjLP-YnmMEGfp55TKLOaIbNHUbGVw2f9SOjjQ
WaYZY6C6AT5ghr-gwlFIljgkNNssgayLdLDXL4M2HjfnOh3qTawgyaTKQDtkuIKY598Zk8XA4IL7fXEkuf-iObEvAnXrCKASgSe3JsSpEvPk13zBDP1hLIOP
12D88obBXaIa-Z-iMZhMV1LSuH934N9dM690RgWNwCfrbOev2BXNbIW3t2IuEnnTUrqsWwJB23b3H383GWQNqGx7eMcVzrLyW2hLuMlprxxVVZXMuNnLdvxI
rhhve0fzR51bSjGQcI6XEPFnb_eXcRNzuRXFDJw3ejmbyv2SBaOaEELoTqNTESEbex7Eg3IWYeZZTrH4k3p2JUuHeUDdlQP4u3ZDyHaSLvcaeoY4_Vo7Z6KG
9O6Wn1eNxSJzwcqLtvx1VlhihVwVh-f7xeqxGjkSU4CUKm46QwyEi6JrylWHcDcnhrjOhUVflk87LSZkcSbS4GhHSzra9RZdyEmUiEpXaiZgkaB54b445O_Y
xehYENiMu96pbnnLLNqH7jPGirK8TwV1AQSB3BdJQNKJgbT8SecGkrNKV5Lhg3QCTgnjW_hruo7PVkugLNhfP_-tNNjNQFkBPl3dMxlXk3WM-x6ajZJUDNTH
k8CXDqiC3uVJNI7LRm_MNRqCY7yMAqsh5JoaN0ei8Jmg8qgu8kZAnJr2sJsxfAvIyrGAKPvXng2x2UxkKiZbeNfnB6YzVast0vRCO9OChP5Qskx7LARhLEEP
h6gFltGYCrJ_6VjbiPgwzW7wd56rW6YV6c8mCrHzrRwYIi-lsggUHV8hgZX9jLLSiA_cOBPggsgUJRLLMxLLMxLLm5OjSO9slufhglWCjTftXls6l9yuMxLL
yrrRjLLhlicGJwpYhjK3LUEPgPBuoAod0XPGhNk2ZqQTKiqQm3CgO67LLgtVL_DTMpLksRMwN-NSggrQfTjhbbHXHHLcvAGAat9AXSLKG5DDFa6E1vo4wbHh
zFhwgZKwoqweK5DNJa0zcsfQrbJX2LIpOMOhge2j6YQjfx8bLJ0REC6jmfegh7TlDrjLXVLKDVDLMpKLXQTvlyBKc6tLv1ES95bHXHEgXK-GlARRNvv1jP-3
uvxvgbXPzVnFd7s2m88ghAZ21LbFLJrVKRLLv4pGSYhWRXLdgd2F2dLPxWG1eYwpIUCgJ55PPM5OXTRe3KK-N8KnbIJzW167RaJr_-BhHKcH5GO0g0JoXDxx
_tzxao0rsZfRxRJZnhTLKCUGnh3VvcZT7mxEEzJVLCnnlmcUZvTKVFSvlZgl8iwW-VIw2c_gO86Ozgg89oeFucUi5Kk5h-QAbugNwbcksdgJCK-f6Y4Yp8yg
8ibC2S_SuKigpYoj-_U5sLgYheNixy7w69l765s5xr4t2Pkhb_a_70cuLoNgUR2OTLCLGWGRsvyPcxlucKfkLFIoAYItAiebsmU93Gzd2HD23zH_axKDvMVL
zVl_qAJXY2MpL8rjWdQipxPNf6CkbeSkrOYFOmjh5_xyAOAa1wghUAYaQkkc7kOk3-EFev1iInGJUmWZvBMdPkQkiGrFrkUxOuwYwX8YDU5GTNMLvaNPNJNq
0VJhAl7g6PfvSeSGmJ3dYMWVpXhZMRr_eAnYZNAh3WTJxQhcIF_KixR-bShugjg6grIrwwofVEd_GcMH8H5X2OSGgEZe5lj2gdfN-hYAewnTfFwQkm28whR5
dl2dQx1CRp3l9BM66FTytQb4pIIgA9D3xT9ozNAxK1Kt2dq-MHI9OhRXOOnmAPH5tdkOcFr11m9lts6wJvtDY4IOMJqOQxbS85Zc9iufwMs1-nBubbmZskoe
oJCLKLgMFu8JIu56bFqNHGaydaSYRdAoEtHyrUCStfx4mnamSfCGS5meraUu-U01s3k1Hvq19GCoIccyvdM0p5GpOk0mEQJ6FihlEM2Ddj48orrSZaRhGoDb
8bIHkPMqHvQoJHRCfZzO3kWUvb-ni2lP5uIiAuMONSbhz6g1kLr-5fuhKn7RDWMopZblhO1EK15PIpdtcWXNhMQrDNQL4ElGU2jm7KqQt_EFLLNCXAFjqU8g
IPMlShFuFkjeLW_Bbme3DBzLKs5n5L3l6ggeaIhpege_L9KQsTPjhwegcWUmQuYZlbIOIvhVpnqvLKDh37PQpL-pglk7ie9BnLygeWPHOIkGTQcosARDdrdC
GS1BvKyrnbxEHgXahyBoiDXNrRm2Aiph3LDLlrGbLETHbtP41NjLARcxD7QLkAgdghggyI-f1BzLrLHbgbBbtsy2gIfNrTjofJlLOwvugUOEjbJ8jog0jwam
LNYl8jYfIAv_gjU0Z4gvWbDrILLM-rbJQNQxCnG8bR8mx3QHbX6SD4qKcyTuMC7Jh2hT3wuMLr6kGLnUQ6g61mQ3vidNKFofkR9X0sB4isk8DlBWRsDqcN_3
8kOiEf9e3THmMXwRMDGqcpSygQ98rUOp-wDRX3AvJ8-fRA6saOTp4oHzXoeE_nePouCFCzSgAd9G5I2LuIZX64mLtwBoOX-iCIzZz0TKuJNL48c42VbOLpLN
qJjoDUAulIqLW0WB7iyLizDInLF5xr5Hh85D5K8zhkhThnMHfQ9SGJchAgdA5ToCP-UKTQKlg5JkSoLnh3eLcDNEwfFFdYxdLPPsHCNcPPcgRQg46uQgdDr5
DrU9hdc9Oruz-6kRPAwkescfg9xzny7yjJDNOH9_FZmlO2vzF0tb6Cr8yePMfcQ7J3R6L35MOZgegiIUBFMdjLzX8yPwLbKehsr_wT8WkfJuroV6OofMLn5m
ZFR1CReH8fnM3SyLpqvczRXCr8wj8DjmLNPdBe7i6OHEgovDOzwONY1G3Lo53GwUacBn4AHtgQNK77r-1MDYKciWPhnKfK4vF1f5M_FHafrCgvwm77tQ1T5J
4IEK0ZbdUMbqzCn4kFh1iaQ_WxRYnF1N1_yF
}
!define DEV_DATABASE(_alias) ENTITY(rectangle,black,combiner_1,_alias,DEV DATABASE)
!define DEV_DATABASE(_alias, _label) ENTITY(rectangle,black,combiner_1,_label, _alias,DEV DATABASE)
!define DEV_DATABASE(_alias, _label, _shape) ENTITY(_shape,black,combiner_1,_label, _alias,DEV DATABASE)
!define DEV_DATABASE(_alias, _label, _shape, _color) ENTITY(_shape,_color,combiner_1,_label, _alias,DEV DATABASE)
skinparam folderBackgroundColor<<DEV DATABASE>> Blue
skinparam RectangleBorderThickness <<DEV DATABASE>> 0
@enduml

